#enable security for Actuator Enpoints
management:
  security:
    enabled: true
logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
      cimmyt: DEBUG
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml
    min-response-size: 20480
spring:
  boot:
    admin:
      url: http://localhost:9090
  datasource:
      #sample manager DB
      initialize: false
      continue-on-error: true
      url: jdbc:postgresql://172.17.61.5:5433/sample_manager
      username: postgres
      password: siu*2016
      dbcp2:
        test-while-idle: true
        test-on-borrow: true
        validation-query: select 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
        order_inserts: true
        order_updates: true
        max_fetch_depth: 1
        default_batch_fetch_size: 8
        id:
          new_generator_mappings: true
        #                cache:
        #                    use_second_level_cache: true
        #                    region:
        #                        factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        jdbc:
          fetch_size: 1000
          batch_size: 10000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false